version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew test
  post_build:
    commands:
      - echo Build completed on `date`
      - ./gradlew clean build -x check
artifacts:
  files:
    - build/libs/search-engine-1.00.jar
    - appspec.yml
  name: $ARTIFACT_NAME
  discard-paths: yes
