version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - ./gradlew clean build -x check
      - ./gradlew checkstyleMain checkstyleTest pmdMain pmdTest
      - ./gradlew test
  post_build:
    commands:
      - echo Build completed on `date`
reports:
  junit-report:
    files:
      - '**/*'
    base-directory: 'build/reports/tests/test'
artifacts:
  files:
    - build/libs/search-engine-1.00.jar
    - appspec.yml
  name: $ARTIFACT_NAME
  discard-paths: yes
