spring:
  application:
    name: search-engine
  profiles:
    active: dev

server:
  port: 8944

flyway:
  locations: db/migration/h2
  schemas: PUBLIC

logging:
  level:
    root: info

---
spring:
  profiles: dev
  datasource:
    url: jdbc:hsqldb:file:./db_storage/sedb_002;MODE=Oracle;AUTO_SERVER=TRUE;hsqldb.sqllog=3
    driverClassName: org.hsqldb.jdbcDriver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
        connection:
          CharSet: utf8
          characterEncoding: utf8
        default_schema: PUBLIC

